In [1]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("One Dimensional array : ",arr1)
print("Two Dimensional array : \n",arr2)

One Dimensional array :  [1 2 3 4 5]
Two Dimensional array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


# Creation using built in methods


In [13]:
xeros=np.zeros((2,3),dtype="int64")
print("zeroes array : ",xeros)

ones=np.ones((3,3))
print("Ones array :",ones)

arr3=np.full((2,3),55)
print("array with 55 only : ",arr3)

arr4=np.eye(3)
print("Prints an identity matrix (which is a square matrix) : ",arr4)

arr5=np.arange(1,10,2)
print("(start,end,skip) : ",arr5)

arr6=np.linspace(1,10,4)
#                (start,stop,the count of numbers wanted)
print("Creates an evenly spaced array : ",arr6)

zeroes array :  [[0 0 0]
 [0 0 0]]
Ones array : [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
array with 55 only :  [[55 55 55]
 [55 55 55]]
Prints an identity matrix (which is a square matrix) :  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(start,end,skip) :  [1 3 5 7 9]
Creates an evenly spaced array :  [ 1.  4.  7. 10.]


# Properties

In [16]:
arr=np.array([[1,2,3],[4,5,6]])

print("dimensions : ",arr.shape)
print("Data type : ",arr.dtype)
print("size : ", arr.size)

float_arr=arr.astype(np.float32)
print("converted to float : ",float_arr)

dimensions :  (2, 3)
Data type :  int64
size :  6
converted to float :  [[1. 2. 3.]
 [4. 5. 6.]]


# Operations on array

1. Reshaping


In [17]:
arr=np.array([[1,2],[4,5],[6,7]])
print("before re-shaping : ",arr.shape)

arr_reshaped=arr.reshape(2,3)
print("after re-shaping :",arr_reshaped.shape)

flattened_Array=arr.flatten()
print("flattened array : ",flattened_Array)

before re-shaping :  (3, 2)
after re-shaping : (2, 3)
flattened array :  [1 2 4 5 6 7]


2. Fancy Indexing and Boolean Indexing

In [21]:
arr=np.array([1,2,3,4,5])

fancy_indexes=[0,1,4]
print(arr[fancy_indexes])

print("Boolean indexing : ",arr[1]%2==0)

[1 2 5]
Boolean indexing :  True


## Axes in Multi-Dimensional Arrays 

Axis in 2-D arrays : axis - 0 =rows performs operations vertically
                     axis - 1=columns performs operation horizontally

In [22]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

sum_of_columns=np.sum(arr,axis=0)
print("col wise sum : ",sum_of_columns)

sum_of_rows=np.sum(arr,axis=1)
print("row wise sum : ",sum_of_rows)

col wise sum :  [12 15 18]
row wise sum :  [ 6 15 24]
